ae = "F:/AI/SD/ComfyUI/models/vae/FLUX1/ae.safetensors"
apply_t5_attn_mask = true
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
caption_extension = ".txt"
clip_l = "F:/AI/SD/ComfyUI/models/clip/clip_l.safetensors"
clip_skip = 1
discrete_flow_shift = 3.1582
dynamo_backend = "no"
enable_bucket = true
epoch = 100
fp8_base = true
full_bf16 = true
gradient_accumulation_steps = 1
gradient_checkpointing = true
guidance_scale = 1.0
huber_c = 0.1
huber_scale = 1
huber_schedule = "snr"
loss_type = "l2"
lr_scheduler = "constant_with_warmup"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_timestep = 1000
max_train_steps = 400
min_bucket_reso = 256
min_snr_gamma = 7
mixed_precision = "bf16"
model_prediction_type = "raw"
network_alpha = 64
network_args = [ "train_double_block_indices=all", "train_single_block_indices=all", "train_blocks=single",]
network_dim = 64
network_module = "networks.lora_flux"
network_weights = "F:/AI/SD/training/aidkad_lora_flux/aidkad-flux_TMP.safetensors"
noise_offset = 0.05
noise_offset_type = "Original"
optimizer_args = [ "relative_step=False", "scale_parameter=False", "warmup_init=False",]
optimizer_type = "Adafactor"
output_dir = "F:/AI/SD/training/aidkad_lora_flux"
output_name = "aidkad-flux"
pretrained_model_name_or_path = "F:/AI/SD/ComfyUI/models/unet/flux1-dev-fp8-e4m3fn.safetensors"
prior_loss_weight = 1
resolution = "512,512"
sample_every_n_steps = 50
sample_prompts = "F:/AI/SD/training/aidkad_lora_flux\\sample/prompt.txt"
sample_sampler = "euler"
save_every_n_epochs = 1
save_every_n_steps = 100
save_model_as = "safetensors"
save_precision = "bf16"
sdpa = true
split_mode = true
t5xxl = "F:/AI/SD/ComfyUI/models/clip/t5xxl_fp8_e4m3fn_scaled.safetensors"
t5xxl_max_token_length = 512
text_encoder_lr = [ 0.0004, 0.0004,]
timestep_sampling = "shift"
train_batch_size = 1
train_data_dir = "F:/AI/SD/training/aidkad/img"
unet_lr = 0.0004
wandb_run_name = "aidkad-flux"
